### ISSUE TITLE
the intro has a mathematical error

### ISSUE THREAD

**Issue by ofloveandhate** [mgruddy/gitpractice#3]
the error is that the exponent is supposed to be 2 instead of 3

**Comment by ofloveandhate** [comment]
i think this was introduced in #2

**Comment by ofloveandhate** [comment]
actually, it's in e998a77a6dfce85b4ff6486ba8628d6b867e5ff2

**Comment by ofloveandhate** [comment]
🌵

**Comment by mgruddy** [comment]
I've edit the code to make sure the exponent is 2.
